name: Release

on:
  push:
    branches:
      - "main"

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-go@v2
        with:
          go-version: '^1.17'

      - name: Build arm64 Linux
        run: |
          env GOOS=linux GOARCH=arm64 go build -o build/linux-arm64

      - name: Build amd64 Linux
        run: |
          env GOOS=linux GOARCH=amd64 go build -o build/linux-amd64

      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          files: |
            build/linux-arm64
            build/linux-amd64
